# Generated by Django 4.2 on 2025-06-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
