# Generated by Django 4.2 on 2025-06-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPosts',
            new_name='BlogPost',
        ),
    ]
