# Generated by Django 4.2 on 2025-06-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['publish_date', 'updated', 'timestamp']},
        ),
    ]
